README.md

Hey,i noticed that we can improve the ReadMe a bit

Contributor List Added

---

Anubhav-Vardhan/README.md

Hey @saiyam1814 I watched [Golang Tutorial for Beginners | Full Go Course (TechWorld with Nana)](https://youtu.be/yyUHQIec83I) and made [Ticket Booking App](https://github.com/anubha-v-ardhan/My-DevOps-Journey/tree/main/01-Prerequisites/Go) following her tutorial, understood the concepts well :)
Can you please recommend what else can I do to get fluent in Golang (some projects or something) or should I move ahead in the roadmap with little practical Golang experience for now.

Progress update for 4 Jan 2021 (Day 2)

---

nawaz-siddiqui/README.md

Created readme

---

Anubhav-Vardhan/README.md

Started learning Linux from scratch :)

Progress update for 5 Jan 2021 (Day 3)

---

Anubhav-Vardhan/README.md

Completed chapter 2 from Intro to Linux. Learnt about the philosophy behind Linux, How the Linux community of developers and the wider community of users work together, Linux's history and its key units like distributions, kernel, file systems etc.

Progress update for 06 Jan 2021 (Day 4)

---

nawaz-siddiqui/README.md

Updated README.md

---

Anubhav-Vardhan/README.md

Thanks Saiyam, Going well so far :)

Progress update for 7th and 8th Jan 2021 (Day 5 and 6)

---

Atir Nayab/README.md

I wish I knew earlier that learning in public, being part of a community is so mush beneficial.
Thanks Saiyam for showing us the light.

day 1 progress

---

Syed-Atif/README.md

Started my journey on DevOps with #learnwithSaiyam

Day-1 of DevOps

---

Atir Nayab/README.md

Is there any free course for linux on edx. [Link](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbE5QMkFyVWhtQWp1UDNxRGtjdHN4UnhpbkxOUXxBQ3Jtc0ttRnozNHZaSTlZaXkxeWVGVXF4bVBBbGE1bVA2MnJVWHR5V3h4Sm8zdC04YzU3b3ZWWElaMzU4ajl1M1plbVluZy1yMUFac2xaMS10NDd4MjFLcGxMMUVSbXVoQVBRaWRzRExXOFBmME50NDctY2lUNA&q=https%3A%2F%2Fwww.edx.org%2Fcourse%2Fintroduction-to-linux) you mentioned is paid one, and has 7 day trail period with limited access.

day 2 progress

---

Anubhav-Vardhan/README.md

Made a site https://anubha-v-ardhan.github.io/ to write blogs and share my learnings
Also had revision of Containerization and Docker concepts learnt last year (still need to learn properly)
Finished Chapter 7 from LFX101x, Linux terminal is easy!

Progress update for 10-Jan-2021 (Day 7)

---

Anurag_Kumar/CCNA/basics.md

Day 3 Progess Update. Started with CCNA course. Targeting to complete it before Monday (At least part 1).

day 3 devops 2022

---

Vaibhav-Patel/Notes.md
Vaibhav-Patel/README.md

Got Familiar with Linux Distributions.

Chapter Two

---

Anubhav-Vardhan/README.md

Wrote a [Blog on YAML](https://anubha-v-ardhan.github.io/blog/introduction-to-yaml/)
No progress in learning new things due to exams :(

Progress update for 12-Jan-2022 (Day 8)

---

Anubhav-Vardhan/Day-001/YAML-notes.md
Anubhav-Vardhan/Day-009/helloworld/main.go
Anubhav-Vardhan/README.md

Started learning Golang from Udemy course [Go: The Complete Developer's Guide](https://www.udemy.com/course/go-the-complete-developers-guide/)
Also, adding my notes here :)

Progress update for 13-01-2022 (Day 9) and notes

---

Anurag_Kumar/Git/gitcommands.md
Anurag_Kumar/Progress/005/Readme.md
Anurag_Kumar/README.md

day 5 devops 2022

---

Anurag_Kumar/Linux/Networking/uptime&PS.md
Anurag_Kumar/Progress/006/Readme.md
Anurag_Kumar/README.md

Learnt about linux processes and two commands about linux (uptime and ps)

 day 6 devops 2022

---

RaviTeja-Natchireddi/README.md

Created a folder to track my progress

Added my day-1 progress

---

Atir Nayab/18-01-2022/ch7.md
Atir Nayab/18-01-2022/ch8.md
Atir Nayab/18-01-2022/ch9.md
Atir Nayab/19-01-2022/ch10.md
Atir Nayab/19-01-2022/ch9.md
Atir Nayab/README.md

This edx linux fundamentals is an amazing course to get basics strong.

day 9 progress

---

Anubhav-Vardhan/Networking/01-Introduction.md
Anubhav-Vardhan/Networking/02-Topologies.md
Anubhav-Vardhan/Networking/03-OSI-Model.md
Anubhav-Vardhan/README.md

I'm back on track after being absent for about a week due to exams at university
Understood basic networking terms, topologies and starting with OSI model. Notes attached :)

Progress update for 22-Jan-2022 (Day 12)

---

Anurag_Kumar/IaC/IaC-Intro.md
Anurag_Kumar/Progress/009/Readme.md
Anurag_Kumar/README.md

day 9 devops

---

Siddhant_Prateek/Linux/README.md
Siddhant_Prateek/README.md

Siddhant's DevOps Journey 

---

Anurag_Kumar/IaC/terraform.md
Anurag_Kumar/Progress/010/Readme.md
Anurag_Kumar/README.md

day 10 devops

---

Darshna_Das/Day_2/Day-2.md
Darshna_Das/Day_3/Day-3.md
Darshna_Das/Day_4/Day-4.md
Darshna_Das/Day_5/Day-5.md
Darshna_Das/Day_6/Day-6.md
Darshna_Das/Day_7/Day-7.md

Day_7 progress

---

Darshna_Das/Day_2/Day-2.md

Day_2 progress

---

Darshna_Das/Day_2/Day-2.md
Darshna_Das/Day_3/Day-3.md
Darshna_Das/Day_4/Day-4.md

Day_4-progress

---

Darshna_Das/Day_2/Day-2.md
Darshna_Das/Day_3/Day-3.md
Darshna_Das/Day_4/Day-4.md
Darshna_Das/Day_5/Day-5.md

Day_5 progress

---

Darshna_Das/Day_2/Day-2.md
Darshna_Das/Day_3/Day-3.md
Darshna_Das/Day_4/Day-4.md
Darshna_Das/Day_5/Day-5.md
Darshna_Das/Day_6/Day-6.md

Day_6 progress

---

Anubhav-Vardhan/Networking/03-OSI-Model.md
Anubhav-Vardhan/Networking/04-TCP_IP-Model.md
Anubhav-Vardhan/Networking/05-Application-layer.md
Anubhav-Vardhan/README.md

Learnt about OSI and TCP/IP model, will do each layer in detail now

Progress update for 29 Jan 2022 (Day 13)

---

Anurag_Kumar/Golang/Basics/arrays.go
Anurag_Kumar/Golang/Basics/hello.go
Anurag_Kumar/Golang/Basics/variables.go
Anurag_Kumar/Progress/011/Readme.md
Anurag_Kumar/Progress/012/Readme.md
Anurag_Kumar/Progress/013/Readme.md
Anurag_Kumar/README.md

day 13 devops

---

RamanandPrabhu/Day1/README.md
RamanandPrabhu/README.md

Please add my changes to upstream

Initial commit

---

Atir Nayab/31-01-2022/git.md
Atir Nayab/README.md
Atir Nayab/devops-roadmap.md

day 19 progress

---

Anurag_Kumar/Golang/Basics/slices.go
Anurag_Kumar/Golang/Basics/variadic-functions.go
Anurag_Kumar/Progress/015/Readme.md
Anurag_Kumar/README.md

day 15 devops

---

RamanandPrabhu/Day2/README.md

Day2- Introduction to Linux

---

Atir Nayab/01-02-2022/cloudPractitioner.md
Atir Nayab/README.md
Atir Nayab/devops-roadmap.md

started AWS Certified Cloud Practitioner Certification Course

day 21 progress

---

nawaz-siddiqui/Kubernetes/basics.md
nawaz-siddiqui/Progress/Day25.md

Learned basics of Kubernetes and deployed nginx using minikube and kubectl

Added day 25 learnings

---

RamanandPrabhu/Day3/README.md

Day3- Linux Filesystem and boot process 1/n

---

nawaz-siddiqui/Kubernetes/Kubernetes techworld with nana.md
nawaz-siddiqui/Progress/Day26.md

Learned and deployed application on my local machine

Added Day 26 learnings

---

RamanandPrabhu/Day4/README.md

Day4- Linux Filesystem and boot process 2/n

---

Anubhav-Vardhan/Go/Notes/003-Functions.md
Anubhav-Vardhan/Go/cards/main.go
Anubhav-Vardhan/README.md

Progress update for 5th Feb 2022 (Day 14)

---

Nawaz-Siddiqui/Kubernetes/Kubernetes techworld with nana.md
Nawaz-Siddiqui/Progress/Day28.md

Learned Helm, ingress and ingress controller, persistent storage claim

Added day 28 learnings

---

RamanandPrabhu/Day5/README.md

Day5 Fundamentals of Containers

---

Nawaz-Siddiqui/Golang/Golang Practice 1.md
Nawaz-Siddiqui/Progress/Day29.md

Added day 29 learnings

---

RamanandPrabhu/Day6/README.md

Day6 Continued Fundamentals of containers

---

Anurag_Kumar/Golang/Basics/functions.go
Anurag_Kumar/Golang/Basics/maps.go
Anurag_Kumar/Golang/Basics/mapsiteration.go
Anurag_Kumar/Golang/Basics/struct.go
Anurag_Kumar/Progress/020/Readme.md
Anurag_Kumar/README.md

day 20 devops

---

RamanandPrabhu/Day7/README.md

Day7 Introduction to Linux Chap 3 complete

---

RamanandPrabhu/Day8/README.md

Day8 Completed Chapter4 on GUI in Linux

---

Nawaz-Siddiqui/Kubernetes/Kubernetes techworld with nana.md
Nawaz-Siddiqui/Progress/Day30.md

Learned about various Kubernetes services

Added Day 30 learning

---

Anurag_Kumar/Linux/basic commands/vim-editor.md
Anurag_Kumar/Progress/022/Readme.md
Anurag_Kumar/README.md

day 22 devops

---

RamanandPrabhu/Day9/README.md

Day9 Linux Command Line

---

Anurag_Kumar/Golang/Basics/receiver-functions.go
Anurag_Kumar/Progress/023/Readme.md
Anurag_Kumar/README.md

day 23 devops

---

RamanandPrabhu/Day10/README.md

Day10 Continued Command Line Operations

---

RamanandPrabhu/Day11/README.md

Day11 Containers continued

---

Shiwam Verma/README.md
Shiwam Verma/day06/day6.md

Completed the pre-requisites , almost. Thinking to skip linux course by edx , It will take too much of time.
I can learn linux more when using it. 
Entering  Advanced stuff tomorrow.

Added Day 6 progress

---

Anurag_Kumar/Gitops/argo-project.md
Anurag_Kumar/Progress/024/Readme.md
Anurag_Kumar/README.md

day 24 devops

---

RamanandPrabhu/Day12/README.md

Day12 Basic operations on files and directories

---

RamanandPrabhu/Day13/README.md

Day13, Standard Streams

---

Anurag_Kumar/Kubernetes/logging/fluentd.md

- Learnt about fluentd and logging in kubernetes

day 25 progress

---

Anurag_Kumar/Golang/Basics/strings/stringfunc.go
Anurag_Kumar/Golang/Basics/strings/stringfunction.go

- Learnt about strings in golang 
- different strings functions

strings in golang 

---

Nawaz-Siddiqui/Amazon AWS/Amazon AWS.md
Nawaz-Siddiqui/Progress/Day31.md

set up AWS account and learned some basics

Added day31 learnings

---

Anurag_Kumar/Linux/basic commands/linux-continued.md
Anurag_Kumar/Progress/026/Readme.md
Anurag_Kumar/README.md

- Continued with Linux
- learnt some more intermediate commands

day 26 devops

---

Anurag_Kumar/CCNA/networking-devices.md
Anurag_Kumar/Progress/027/Readme.md
Anurag_Kumar/README.md

day 27 devops 

---

Kunal-Verma/README.md
Kunal-Verma/TABLE-OF-CONTENTS.md

Signed-off-by: Kunal Verma <vkunal321@gmail.com>
Adding my folder, which would mark the start of my DevOps learning journey!

[Add] Kunal-Verma folder

---

Anurag_Kumar/Progress/029/Readme.md
Anurag_Kumar/README.md
Anurag_Kumar/cloudnativetools/security/falco.md

day 29 devops

---

Anurag_Kumar/Linux/Networking/networking.md
Anurag_Kumar/Progress/030/Readme.md
Anurag_Kumar/README.md
Anurag_Kumar/cloudnativetools/security/apparmor.md

- Linux network manager
- Apparmor

Day 30 Devops

---

Shanmukh/Status.md

Added my folder and status.md file to share my daily learnings

added status.md file

---

Aaquib/devops-roadmap.md

DevOps journey begins today...

mdaquib171 added Readme file

---

Anurag_Kumar/Kubernetes/kubernetes-basics/k8s-jobs.md
Anurag_Kumar/Progress/031/Readme.md
Anurag_Kumar/README.md

day 31 devops

---

Sourav Kumar/README.md

sourav added readme file

---

Tanmay-Sarkar/Day1-Golang.md
Tanmay-Sarkar/Readme.md

@saiyam1814 Hello Saiyam Sir, I am very excited about the journey with the guidance you have posted. 
Merge my folder also.

Added my personal folder and started the journey of DevOps in public.

---

CONTRIBUTING.md

proper syntax for highlighting code i.e. ```<code>``` was missing at line 37

Fixed a error in Contributing.md file

---

Shariq/README.md

I'm learning DevOps by following the provided Roadmap & resources in repo, this is my first PR. I will be documenting my progress regularly. Thanks you.

📦 NEW: Add README

---

Shariq/README.md

Finished some items from Prerequisites.

📦 NEW: Add Prerequisites

---

Dipanshu Kumar/Devops Learning status/readme.md
Dipanshu Kumar/Why Devops/readme.md

@saiyam1814 ,You helped me find my passion .
Thank You a lot @saiyam1814 for the amazing work you have been doing.

My first Commit

---

.vscode/settings.json

Create DevOps roadmap 2022.pdf

---

Sunny/Day 1/Day1.md
Sunny/Readme.md

I am Sunny , I have started my DevOps journey and this is my first commit to my documenting journey , learning in public . Please accept my PR.

Day_1 of DevOps

---

Adebisi Olayinka/DAy2.md
Adebisi Olayinka/Day 3 - DAy 10.md

This commit documents my activities for Day 3 through to Day 10

Add Logs for Day 3 - Day 10

---

Prabitra_Sarkar/Checklist.md

I am gonna finish learning this roadmap and I will share my experiences through this repository !

[I am started following the roadmap]

---

Dev-Patel/README.md

Added My Folder 
